### ISSUE TITLE
How to use right click update correctly

### ISSUE THREAD

**Issue by priv** [AppImage/appimaged#100]
Both Use AppImageUpdate and appimaged have description that if they are used together, you can do a neat trick to Update Application using right click on the icon.  If I understand correctly, which means adding something in the Desktop Shortcut items.

However I failed to make it work, so I inspect the code in appimaged, and didn't find anything related to AppImageUpdate besides README.md.

So how does it work actually?

**Comment by TheAssassin** [comment]
AppImageLauncher provides updating from the context menu in a more reliable way. Perhaps you want to give it a try? It's a more holistic approach on AppImage integration into Linux desktops.

https://github.com/TheAssassin/AppImageLauncher

**Comment by munix9** [comment]
I created a small service menu for KDE Plasma/KF5 for the openSUSE package:
https://build.opensuse.org/package/view_file/home:munix9/AppImageUpdate/appimage-update.desktop?expand=1
```
[Desktop Entry]
Type=Service
ServiceTypes=KonqPopupMenu/Plugin
MimeType=application/vnd.appimage;
Actions=check;update;
X-KDE-Submenu=AppImage
X-KDE-Priority=TopLevel

[Desktop Action check]
Name=Check for update
Name[de]=Auf Aktualisierung prüfen
Icon=AppImageUpdate
Exec=kdialog --title "AppImageUpdate" --msgbox "<p>%u</p><p><b>$(AppImageUpdate -j %u 2>&1 | tail -n +2)</b></p>"

[Desktop Action update]
Name=Update
Name[de]=Aktualisieren
Icon=AppImageUpdate
Exec=AppImageUpdate %u >/dev/null 2>&1
```
appimage-update.desktop can be stored in `/usr/share/kservices5/ServiceMenus/` (global) or `~/.local/share/kservices5/ServiceMenus/` (user).

But this belongs more to https://github.com/AppImage/AppImageUpdate

AppImageLauncher also sounds interesting.

**Comment by probonopd** [comment]
Thanks @munix9. Please see https://github.com/AppImage/AppImageKit/issues/169.

**Comment by priv** [comment]
Thanks and closing this issue.
