### ISSUE TITLE
AppImage failed to load if using appimaged firejail integrated launchers

### ISSUE THREAD

**Issue by UriHerrera** [AppImage/appimaged#101]
I tested using the releases tagged with commit https://github.com/AppImage/appimaged/commit/0f1c320b0905a960520816cd36b7eec9ff79484c. Both the Debian packages and the AppImage.

If I click on the AppImage without using the launcher `.desktop` that appimaged creates the AppImages launches without a problem.

If I use the launcher that appimaged creates, I get the resulting error.

![VirtualBox_Nitrux_26_11_2019_21_41_07](https://user-images.githubusercontent.com/3053525/69692441-ae623800-1097-11ea-8eee-2d8e8b02bcd4.png)

I tested with Nitrux 1.2.2 using kernel 5.4 and firejail 0.9.60.

---- 

I then tested using a previous kernel 5.3.13 (of all things), and the same AppImage works with the same firejail version and using the AppImage of appimaged of the same commit as before.

![VirtualBox_Nitrux_26_11_2019_23_23_52](https://user-images.githubusercontent.com/3053525/69695986-deafd380-10a3-11ea-87d3-dfef85c5bd48.png)

**Comment by probonopd** [comment]
So you are saying kernel 5.4 breaks Firejail? Sounds like an issue to be reported over at https://github.com/netblue30/firejail then?

**Comment by UriHerrera** [comment]
You're right; it's not an issue caused by appimaged.
