### ISSUE TITLE
Not running from within an AppImage. This binary cannot be installed in this way.

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [AppImage/appimaged#102]
Hello, installed the package from opensuse repo. When running with 
"appimaged -i some.appimage", I get this error. The appimage application runs fine by itself though.

**Comment by probonopd** [comment]
What gave you the impression that you should run `appimaged -i some.appimage`? Where do you have this command from and what do you think it should do?

**Comment by GreatBigWhiteWorld** [comment]
Application Options:
  -i, --install       Install this appimaged instance to $HOME

I installed the appimaged package from opensuse official repo, thinking it would work automatically if I put all my .appimage apps under $HOME/Applications. Until after a few days nothing happened.

In fact, when I ran an appimage they used to ask me if I want to register to the system. That was long time ago, long before I know anything about appimaged. But they stopped asking me the questions some time ago for unknown reasons.
Then I find this appimaged which I thought would monitor certain directories.
How do I use it then?

**Comment by probonopd** [comment]
Ah, that clarifies it. I didn't remember that openSUSE was packaging appimaged. If you install it from a rpm then you don't need to use `-i, --install`. This option is only for when running appimaged from an AppImage. In fact, the message even says so.

I guess the option 

```
Application Options:
-i, --install Install this appimaged instance to $HOME
```

should only be shown if appimaged is running from an AppImage.

**Comment by GreatBigWhiteWorld** [comment]
I ran "appimaged" under $HOME/Applications to let it register the appimages there but it registered some from the ~/Downloads directory that I forgot to delete after downloading and it kept running for quite a while. 
So I force stopped it and ran 'appimaged -v', only to find out it was doing a whole scale search on my hard drive like an anti-virus.
Is it possible to let it just register the directory I tell it to??

**Comment by probonopd** [comment]
No.
