### ISSUE TITLE
Can't install RPM due to conflict with hicolor-icon-theme

### ISSUE THREAD

**Issue by kbknapp** [AppImage/appimaged#109]
Been using this on Ubuntu for quite some time, but recently set up a new work laptop using Fedora (32) KDE Spin. Upon attempting to install the RPM I get this message:

```
Error: Transaction test error:
  file /usr/share/icons/hicolor/128x128 from install of appimaged-appimaged-1_alpha-gitccddaad~travis220.x86_64 conflicts with file from package hicolor-icon-theme-0.17-8.fc32.noarch
  file /usr/share/icons/hicolor/128x128/apps from install of appimaged-appimaged-1_alpha-gitccddaad~travis220.x86_64 conflicts with file from package hicolor-icon-theme-0.17-8.fc32.noarch
```
I see #95 mentions hicolor, but I don't know if it's related or not.

**Comment by probonopd** [comment]
Uh, that's really bad. Sorry you are running into trouble. Does the AppImage version work for you? 

Maybe we should drop the rpm/deb packages altogether and just ship appimaged as an AppImage only. That's what I intend to do for the upcoming successor, anyway.

**Comment by kbknapp** [comment]
The AppImage version does work. 

The one bit of feature parity between them is I liked how the deb version uses systemd (auto)start. I guess it's not out of the realm of possibility to simply add a `--user` systemd unit file manually, but it was nice that the deb did it automatically. I'm assuming the same for the rpm? Although due to this bug I couldn't check it out :stuck_out_tongue_winking_eye:

**Comment by TheAssassin** [comment]
I think I know what the issue is. RPM doesn't like "empty directories" to be "installed". It's a nonsense limitation, and requires blacklisting all those directories in CMake's CPack configuration.

@probonopd please add all the directory names in https://github.com/AppImage/appimaged/blob/master/cmake/cpack_rpms.cmake#L31, that should fix the problem.

**Comment by TheAssassin** [comment]
The other issue is by the way *not* related.

**Comment by probonopd** [comment]
Interesting,

```
/usr/share/icons/hicolor/128x128 
/usr/share/icons/hicolor/128x128/apps
```

are not files (at least they shouldn't) but directories.

**Comment by TheAssassin** [comment]
IMO a bug/limitation in CMake. They should ignore directories automatically, they would be created automatically anyway. Not sure if the bug is known upstream, don't have time to look into that.

**Comment by probonopd** [comment]
@kbknapp can you please retest with the latest continuous build? Thanks.

**Comment by kbknapp** [comment]
I just tested with `appimaged-appimaged-1_alpha-gitb096cd3.travis221.x86_64.rpm` and it works :tada:

**Comment by probonopd** [comment]
Thanks for confirming @kbknapp and thanks for providing the solution @TheAssassin
