### ISSUE TITLE
Link libappimage statically

### ISSUE THREAD

**Issue by probonopd** [AppImage/appimaged#11]
appimaged_1-alpha-gitabc1464.travis9_amd64.deb should link libappimage statically since the library does not have a stable public ABI yet

**Comment by probonopd** [comment]
And, more importantly, so that one can install it by double clicking the deb, without having to install a deb for libappimage first

**Comment by TheAssassin** [comment]
Change `libappimage_static` for `libappimage` in the CMake configuration in `src`.

But I think libappimage is bundled by our AppImages, isn't it?

**Comment by TheAssassin** [comment]
> And, more importantly, so that one can install it by double clicking the deb, without having to install a deb for libappimage first

I agree this is indeed an issue. Please implement the fix I suggested above, it'll link libappimage statically then.

**Comment by probonopd** [comment]
Build fails with

```
[100%] Linking C executable appimaged
/usr/bin/ld: ../lib/AppImageKit/src/libappimage_static.a(notify.c.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

now.

**Comment by probonopd** [comment]
This currently breaks https://github.com/probonopd/SystemImageKit/blob/master/boot/bin/generate-appimaged-extension.

Never touch a...

**Comment by TheAssassin** [comment]
https://travis-ci.org/AppImage/appimaged/builds/390200745#L3114

Now that we don't build libappimage any more, we don't need to install it with CMake.

I still don't believe that installing an appimaged package was _really_ necessary earlier, @probonopd.

**Comment by azubieta** [comment]
> Now that we don't build libappimage any more, we don't need to install it with CMake.
Are we going to keep building and installing libappimage from AppImageKit ?

**Comment by TheAssassin** [comment]
@azubieta this issue is about distributing libappimage for this specific app. We wouldn't discuss such things in any repo but AppImageKit.
