### ISSUE TITLE
Failed to change to directory "~" (no such file or directory)

### ISSUE THREAD

**Issue by ackhack** [AppImage/appimaged#111]
I download osu! from https://github.com/ppy/osu/releases and appimaged automatically installed it as expected. Trying to lauch it via the menu says:

Failed to launch "osu!"
Failed to change to directory "~" (no such file or directory)

Running on appimaged, continous build (commit b096cd3), build 221 built on 2020-03-30 19:16:46 UTC.
cd ~ works in terminal.

**Comment by probonopd** [comment]
Please report issues with osu at https://github.com/ppy/osu/issues, thank you.
