### ISSUE TITLE
I can't install it

### ISSUE THREAD

**Issue by PERCE-NEIGE** [AppImage/appimaged#114]
I am on Peppermint 10, 32 bits.

I did: wget "https://github.com/AppImage/appimaged/releases/download/continuous/appimaged-x86_64.AppImage"
sudo chmod a+x appimaged-x86_64.AppImage from my download folder.  
sudo ./appimaged-x86_64.AppImage --install

It gives this output ("�" are part of the output I copy/paste):  
./appimaged-x86_64.AppImage: 1: ./appimaged-x86_64.AppImage: �: not found
./appimaged-x86_64.AppImage: 2: ./appimaged-x86_64.AppImage: }�P7pysH��_f��h: not found
./appimaged-x86_64.AppImage: 1: ./appimaged-x86_64.AppImage: �b��@@: not found
./appimaged-x86_64.AppImage: 1: ./appimaged-x86_64.AppImage: ELFAI: not found
./appimaged-x86_64.AppImage: 19: ./appimaged-x86_64.AppImage: Syntax error: Unterminated quoted string

**Comment by probonopd** [comment]
> I am on Peppermint 10, 32 bits.

Then you should better not try to run an x86_64 binary.
