### ISSUE TITLE
Tagged Releases

### ISSUE THREAD

**Issue by Mailaender** [AppImage/appimaged#117]
https://build.opensuse.org/package/show/system:packagemanager/appimaged currently gets a released version 10 from https://github.com/AppImage/AppImageKit where it was apparently moved. I would like to see a version 11+ here. The current `continuous` and `videos` tags are not valid versions by any definition.

**Comment by probonopd** [comment]
Hi @Mailaender that's me to blame - we have no one to act as a "release manager" for https://github.com/AppImage/appimaged/  and all I am basically interested in is `master`/continuous builds, as I do not want to invest time in maintaining anything but the `master` branch. I know it's a controversial position...

That being said,  https://github.com/AppImage/appimaged/  doesn't really see any active development anymore as I am now focused on its Go-based replacement over at https://github.com/probonopd/go-appimage/tree/master/src/appimaged.

**Comment by probonopd** [comment]
Would using something like 0.20200628 or whatever the current date is work for you? This should possibly even be compliant with semver.

**Comment by Mailaender** [comment]
I see. https://software.opensuse.org/package/appimaged is currently shipping version 9 and the build server has 10. Going to 0.something will cause problems.

**Comment by probonopd** [comment]
Focusing on https://github.com/probonopd/go-appimage/tree/master/src/appimaged from now on.
