### ISSUE TITLE
Question about a sensitive bug in appimaged

### ISSUE THREAD

**Issue by refi64** [AppImage/appimaged#118]
Hello:

I sent you an email a few days ago about a bug in appimaged with nasty consequences. As I haven't yet gotten a reply, I wanted to make sure it didn't just get lost accidentally, as I couldn't find any other contacts other than your email online :sweat_smile:

**Comment by probonopd** [comment]
Thanks for the ping. Have responded over mail. I have also notified the current libappimage maintainer.
