### ISSUE TITLE
AppImageLauncher

### ISSUE THREAD

**Issue by maverick74** [AppImage/appimaged#119]
@TheAssassin 's AppImageLauncher has some very interesting features that, i think, would make perfect sense to be part of AppImage.

Is this deamon implementing some of those features?

Why not merge both?

(i honestly don't remember if i already asked something like this, so... i'm sorry if i already have)

**Comment by probonopd** [comment]
AppImageLauncher and appimaged have different UX philosophies:
* AppImageLauncher asks the user questions
* appimaged never asks the user any questions, it is designed to "just work" in the background

So you choose the one you like better.
