### ISSUE TITLE
TODO: Implement inode.base.inode_type 9

### ISSUE THREAD

**Issue by probonopd** [AppImage/appimaged#13]
jdevera at https://github.com/AppImage/AppImageKit/issues/806:

When appimaged is processing the Digikam appimage, it complains about the lack of Exec key in the found desktop file:

```
Jun 15 23:47:24 nexon appimaged[15311]: -> REGISTER /home/jdevera/.local/bin/digikam-5.9.0-01-x86-64.appimage
Jun 15 23:47:24 nexon appimaged[15311]: squashfs based type 2 AppImage
Jun 15 23:47:24 nexon appimaged[15311]: Got root desktop: digikam.desktop
Jun 15 23:47:24 nexon appimaged[15311]: TODO: Implement inode.base.inode_type 9
Jun 15 23:47:24 nexon appimaged[15311]: Desktop file has no Exec key
```

However, the `digikam.desktop` file inside the appimage contains the following line:

```
Exec=digikam.wrapper -qwindowtitle %c
```

The result is that no desktop entry is registered for Digikam

**Comment by probonopd** [comment]
> the Digikam appimage

Can you please provide a download link to that particular version of "the Digikam appimage"?

**Comment by probonopd** [comment]
https://download.kde.org/stable/digikam/digikam-5.9.0-01-x86-64.appimage.mirrorlist

**Comment by stephaniestroka** [comment]
I have the same issue with my application. Desktop file:
```[Desktop Entry]
Type=Application
Name=BitBox
Exec=BitBox
Icon=bitbox_icon
Comment=Manage your crypto assets
Categories=Utility;
Terminal=false```

Running appimaged results in:
```-> REGISTER /home/stephanie/Downloads/BitBox-x86_64.AppImage
squashfs based type 2 AppImage
Got root desktop: bitbox.desktop
TODO: Implement inode.base.inode_type 9
Desktop file has no Exec key```

**Comment by probonopd** [comment]
Which distribution and version did you produce the AppImage on, and using which filesystem (ext4? btrfs?)

**Comment by stephaniestroka** [comment]
I have Fedora 26, filesystem: ext4. I produced the appimage on a docker image running Ubuntu 14.04.

**Comment by probonopd** [comment]
What filesystem does the Docker image use?

**Comment by TheAssassin** [comment]
@probonopd none.

**Comment by probonopd** [comment]
We need to make sense of and implement:

``` 
The uid and gid indexes are 4 bits in length.  Ordinarily, this will allow 16
unique indexes into the uid table.  To minimise overhead, the uid index is
used in conjunction with the spare bit in the file type to form a 48 entry
index as follows:

	inode type 1 - 5: uid index = uid
	inode type 5 -10: uid index = 16 + uid
	inode type 11 - 15: uid index = 32 + uid
```

Source: https://github.com/ddollar/squashr/tree/master/ext/squashfs3.4

References:
* https://github.com/AppImage/AppImageKit/issues/498
* https://github.com/AppImage/AppImageKit/issues/279 (even more strange inode types

**Comment by probonopd** [comment]
Actually, this is not an `appimaged` issue since:

```
Downloads/digikam-5.9.0-01-x86-64.appimage --appimage-extract
(...)
squashfs-root/usr/share/showfoto/breeze-dark.rcc
TODO: Implement inode.base.inode_type 10
squashfs-root/usr/share/showfoto/breeze.rcc
TODO: Implement inode.base.inode_type 10
```

**Comment by probonopd** [comment]
Seems to be fixed in `runtime.c` https://github.com/AppImage/AppImageKit/commit/ae9677b6eca0c1d42d7070caf40f1a90b64e997a now.

**Comment by probonopd** [comment]
Is now fixed everywhere but in https://github.com/AppImage/libappimage/blob/master/src/libappimage/type2.c
