### ISSUE TITLE
Is there an easy way to change the folders monitored without recompiling the application?

### ISSUE THREAD

**Issue by thedonquixotic** [AppImage/appimaged#17]
Hey, sorry, huge newbie here but I was wondering if it was possible to add a custom directory to be monitored by the application?

**Comment by thedonquixotic** [comment]
I made a custom folder under Home called "Apps" that I planned on putting all my AppImages into. I tried to copy and paste it over into the usr/local/bin folder but was denied access. I know that I can do it via cp in CLI but I figured that it would be easier to just copy and paste it over to a folder I already had access to. Not sure why it wouldn't give me access to copy and paste over to the bin folder but I imagine that's because of a permissions thing. It didn't ask me for my sudo login though, it just denied it. 

I'm using Dolphin on a new installation of Kubuntu 18.04. I'm new to using Linux full time, I'm a designer learning to code so I'm trying my best but I'm also pretty behind compared to a lot of people!

**Comment by probonopd** [comment]
Wouldn't one of the monitored directories at https://github.com/AppImage/appimaged/#monitored-directories work for you?

**Comment by TheAssassin** [comment]
`$HOME/Applications` is the recommended directory. It's used by all alternative tools as well (most prominently AppImageLauncher (https://github.com/TheAssassin/AppImageLauncher)).

**Comment by thedonquixotic** [comment]
Ah yeah, I've added it to Applications now but it isn't showing up when I search in KDE's program launcher. Maybe just need to restart. Thanks guys! I'll also check out the AppImageLauncher.

**Comment by probonopd** [comment]
It may be necessary to log out and log in again for it to fully work. Let us know if it is not.

**Comment by thedonquixotic** [comment]
Hey by the way guys, I can confirm that Applications is working great now. Thanks!

**Comment by TheAssassin** [comment]
Cool. If you still want to try out AppImageLauncher, please provide some feedback over there or via IRC as well!

**Comment by thedonquixotic** [comment]
Will do!

**Comment by thedonquixotic** [comment]
I hate to sound like an idiot, I'm very new to Linux but how do I install the AppImageLauncher? @TheAssassin Do I need to build it from source or something like that?

**Comment by thedonquixotic** [comment]
Ooh nevermind. I found it!

**Comment by TheAssassin** [comment]
@thedonquixotic please join our IRC chat (#AppImage on Freenode) or open an issue in the [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher) repository, thanks.
