### ISSUE TITLE
32-bit builds required?

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/appimaged#2]
CC @probonopd 

Should we (again) offer 32-bit builds for appimaged? At the moment, appimaged is built in the standard Travis CI environment (i.e., Ubuntu trusty) in a 64-bit environment.

We could think about building the project using https://github.com/AppImage/AppImageBuild, just like we did before, when it was part of https://github.com/AppImage/AppImageKit.

**Comment by probonopd** [comment]
> Should we (again) offer 32-bit builds for appimaged? 

Yes, I think so, at long as the oldest still-supported LTS mainstream distributions have 32-bit versions.

**Comment by TheAssassin** [comment]
@probonopd if we decide to re-introduce them, then we can just build using AppImageBuild again. That's probably easier.

**Comment by probonopd** [comment]
Yes, why not

**Comment by TheAssassin** [comment]
Cross-compiling 32-bit AppImages and Debian packages now. See https://github.com/AppImage/appimaged/releases.
