### ISSUE TITLE
Implement appimage_shall_not_be_integrated

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/appimaged#20]
Original issue: https://github.com/AppImage/AppImageKit/issues/754

**Comment by probonopd** [comment]
Since it is appimaged that actually does the integration, it should be handled there imho.

**Comment by azubieta** [comment]
It's already implemented there see: https://github.com/AppImage/libappimage/blob/19c2d1ee75e4c41a3aa6bafd17562f8abe890fd0/include/appimage/appimage.h#L117

**Comment by TheAssassin** [comment]
The idea is to call this function in appimaged to respect whether an AppImage does just not want to be integrated (there are tons of valid reasons for that). Right now, this is *optional* for users of libappimage, and only called in AppImageLauncher.

If everyone agrees, we could make this check default in the integration code, removing this function from the public interface and calling it by default in `appimage_{type1,type2}_register_in_system`.

**Comment by azubieta** [comment]
Done at `libappimage` v0.2. Reopen if the issue persists.
