### ISSUE TITLE
32-bit builds missing

### ISSUE THREAD

**Issue by probonopd** [AppImage/appimaged#21]
Since the move into this repository, 32-bit builds are now missing @TheAssassin

**Comment by TheAssassin** [comment]
That's not true. 32-bit builds are created with cross-compilation. See https://github.com/AppImage/appimaged/issues/2. Must be a Travis CI issue.

**Comment by probonopd** [comment]
Looks like the issue was not caused by the move but needs to be fixed nevertheless.

**Comment by TheAssassin** [comment]
Fixed: https://github.com/AppImage/appimaged/commit/f8888181eaf03a2c187bb56c004b79d81b759a6b

Thanks for wasting hours of lifetime, Travis... *again*...

**Comment by probonopd** [comment]
Changing the dependencies is hardly a Travis issue? But anyhow, thanks for fixing it.

**Comment by TheAssassin** [comment]
@probonopd we haven't changed dependencies, they stopped installing a package by default...
