### ISSUE TITLE
[Feature Request] When installing appimaged, let users choose where it will watch.

### ISSUE THREAD

**Issue by ZeroAurora** [AppImage/appimaged#23]
For example, I prefer to install all my AppImages in `~/Applications`. I don't want appimaged to search my `~/Downloads` again and again.
(I'm sorry for my bad English)

**Comment by TheAssassin** [comment]
@ZeroAurora you should switch to AppImageLauncher, which provides the features you need:

 - moves AppImages into `~/Applications` on first run, during desktop integration
 - appimagelauncherd, a daemon, watches target directory for changes
 - no more `chmod +x`, simply double-click (or just click, in a browser for instance) your AppImages, and you will be prompted

For more information, please see https://github.com/TheAssassin/AppImageLauncher.

**Comment by ZeroAurora** [comment]
@TheAssassin Thanks. I've tried it before, but I couldn't install its rpm package by using dnf (on fedora). Maybe I will open an another issue in your project.

**Comment by TheAssassin** [comment]
@ZeroAurora well I don't know whether `dnf` can install "raw `.rpm`" packages. `rpm -i` usually works fine.

Please open an issue, and add some details like the error message and your version of Fedora. An installation issue should be fixed, and shouldn't prevent you from using AppImageLauncher

**Comment by probonopd** [comment]
Hello @ZeroAurora, `appimaged` will always scan the hardcoded directories. If you want configurability, you may consider to switch to [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher/issues/78#issuecomment-422569190) instead.
