### ISSUE TITLE
appimaged loopscan all files in home

### ISSUE THREAD

**Issue by blackPantherOS** [AppImage/appimaged#24]
I tried latest version after build::
..
-> Skipping file /home/build/.ccache/a/7/3ebc5795520dd1b3d811667b71ffa2-221899.stderr
Unrecognized file '/home/build/.ccache/a/7/35df42cef21ca8f2f81c21aee72aa0-1971750.o'
-> Skipping file /home/build/.ccache/a/7/35df42cef21ca8f2f81c21aee72aa0-1971750.o
Unrecognized file '/home/build/.ccache/a/7/01a65572cb4b074af8a9ba745e5b74-876796.stderr'
-> Skipping file /home/build/.ccache/a/7/01a65572cb4b074af8a9ba745e5b74-876796.stderr
Unrecognized file '/home/build/.ccache/a/7/31d45aa27737fc79647612e5f30c34-6353.manifest'
-> Skipping file /home/build/.ccache/a/7/31d45aa27737fc79647612e5f30c34-6353.manifest
..
Why scanning this path? I patched main.c and I tried isolate scanning to ~/bin but seem this is not enough

**Comment by probonopd** [comment]
I don't know why it is scanning there, it is supposed to scan only https://github.com/AppImage/appimaged#monitored-directories

**Comment by blackPantherOS** [comment]
Of course, I know because I see in code as well.. 
Okay, I will remove all patches which we used to previous versions and I will try again.

**Comment by probonopd** [comment]
Does your system have some symlinks in the scanned places, maybe?

**Comment by blackPantherOS** [comment]
Ok, I found the origin of this problem, in main.c 
```
    - add_dir_to_watch(g_get_user_special_dir(G_USER_DIRECTORY_DOWNLOAD));
    +// add_dir_to_watch(g_get_user_special_dir(G_USER_DIRECTORY_DOWNLOAD));
```
The problem is persists If the user own Home directory set as to download destination. I've added this patch and this solve my problem and the our users as well.

**Comment by probonopd** [comment]
It looks like your setup is deviating from what can be considered the usual default:

* The download directory should not be `$HOME` but rather something within it; normally it is `$HOME/Downloads`. Is your somewhat strange setup intentional, and why?
* If you disable watching the downloads directory, freshly downloaded AppImages will not be integrated into the system automatically, is that what you intend, and why?

**Comment by probonopd** [comment]
Do you have a Live ISO available for testing your system?

**Comment by blackPantherOS** [comment]
> "normally it is $HOME/Downloads. Is your somewhat strange setup intentional, and why?"
I want organize files, and don't want many different files in Downloads directory. And I was work on XDG few days ago and we try many different settings. Any problem occurred with XDG, the XDG default value is set to  $HOME. I require be prepared system for any user mistakes as well.

My suggestion to your code, the subdirectory does not exists,it should be removed from watching path,

> "If you disable watching the downloads directory, freshly downloaded AppImages will not be integrated into the system automatically,"
Your first idea is good, but I think not so good place the user's download directory to runing any application. We made a dialog based "first start wizard" this create one '$HOME/.Appimage' directory and a localized symlink to -> '$HOME/Applications'. The appimaged  watching this directory only.
If we provide many AppImage dir to watching, the user can mixing many application version, this is not good and insecure things as well.

"Do you have a Live ISO available for testing your system?"
The old version of course vailable on our ftp servers or webpage. The new beta of next version still not, but will be available in two weeks between. The patched appimaged for beta available here now.
ftp://ftp.blackpantheros.eu/blackPanther/OS/All/v18.x/64bit/media1/appimaged-11~git20181021-1bP.x86_64.rpm

Sry if my English not so good:)

**Comment by probonopd** [comment]
Thanks for the clarification. 

> My suggestion to your code, the subdirectory does not exists,it should be removed from watching path

If one of the directories to be watched does not exist, then it can't (and should not) be watched. Is it not how it is behaving today?

**Comment by blackPantherOS** [comment]
:+1:  Okay, this is a mistake and my bad english, sorry... so, so :) 
I think to this:
`[ "$(xdg-user-dir DOWNLOAD)" == "$HOME" ] && exit 

Its okay?:)

**Comment by probonopd** [comment]
Yes, I see. That's a good idea for your case.
