### ISSUE TITLE
Reimplement signing

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/appimaged#3]
The current builds aren't signed since the extraction. We need to re-implement this.

**Comment by probonopd** [comment]
(note to self, this is exactly the type of "admin" work I don't enjoy doing and why I never touch running setups)

**Comment by TheAssassin** [comment]
"Running" doesn't mean "good" or "suitable". And this is an easy fix, we can just copy the relevant parts from AppImageKit's scripts. We just need the password for that little tarball you download, and enter it into Travis CI's configuration.

**Comment by probonopd** [comment]
Right... which means I need to physically go to my super secure location, retrieve it, and so on ;-)

**Comment by TheAssassin** [comment]
I'm sure there is a way to fetch the value from Travis.

> that I am always either working or traveling doesn't make this easier.

I agree. I understand your situation, but IMO too many things depend on you at the moment. We need to think about solutions. I could imagine moving at least some of such credentials to some protected Wiki. But that's off topic.

**Comment by TheAssassin** [comment]
https://stackoverflow.com/a/44059814
