### ISSUE TITLE
Native distro packages for appimaged

### ISSUE THREAD

**Issue by probonopd** [AppImage/appimaged#43]
EDIT: __Anyone reading this and interested in doing native distribution packages, we are on IRC on #AppImages on irc.freenode.net__

@rickysarraf  writes in https://github.com/probonopd/AppImageKit/issues/325

> I can speak on what is the case in Debian. I'm not sure about other distributions. ON Debian, on the buildd infrastructure, network access is disabled. And there are good reasons to do that. Your git submodules are just defined as a git repository.

I am not sure what is the best path of action here, but I will definitely support anyone who wants to make a native (in the sense of: part of the official debian distribution) debian package for `appimaged`. Also see the great work by @marguerite who has packaged it (and `appimagetool`) for openSUSE.

Perhaps @ScarlettGatelyClark wants to chime in?

Collecting here the need for a debian package:
* https://news.ycombinator.com/item?id=13422925
* https://github.com/LibrePCB/LibrePCB/pull/140#issuecomment-275874481

**Comment by TheAssassin** [comment]
We have those packages now, we ship them already on the release page.

"Real" distro packaging should be treated in a separate issue, or ideally in the trackers of those distros.
