### ISSUE TITLE
 Read of ELF section header from (null) failed: Success

### ISSUE THREAD

**Issue by probonopd** [AppImage/appimaged#48]
`appimaged` exits with

```
_________________________

-> REGISTER /isodevice/Applications/QQ-x86_64.AppImage
squashfs based type 2 AppImage
Read of ELF section header from (null) failed: Success
```

Then `systemd` relaunches it immediately again, resulting in it taking up 100% CPU.

`appimaged -v` does not show much more:

```
_________________________
AppImage type 2

-> REGISTER /isodevice/Applications/QQ-x86_64.AppImage
get_thumbnail_path: /home/me/.cache/thumbnails/normal/74fad7cdf0cb4fd33e0758795bfe48b8.png
squashfs based type 2 AppImage
md5 of URI RFC 2396: 74fad7cdf0cb4fd33e0758795bfe48b8
Read of ELF section header from (null) failed: Success
```

The AppImage in question has some issue:

```
me@host:~$ /isodevice/Applications/QQ-x86_64.AppImage --appimage-extract
Segmentation fault


me@host:~$ /isodevice/Applications/QQ-x86_64.AppImage --appimage-mount
Segmentation fault

me@host:~$ file /isodevice/Applications/QQ-x86_64.AppImage 
/isodevice/Applications/QQ-x86_64.AppImage: ERROR: ELF 64-bit LSB executable, x86-64, version 1, dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2 error reading (Invalid argument)

me@host:~$ ls -lh  /isodevice/Applications/QQ-x86_64.AppImage 
-rwxr-xr-x 1 root root 32K Nov 29 01:26 /isodevice/Applications/QQ-x86_64.AppImage
```

We should
* Make systemd give up after x retries
* Fix the root cause why `appimaged` exits here
* In general, make `appimaged` more resilient so that it never exits, but simply skips AppImages it cannot deal with

[defective_appimage_for_testing.AppImage.zip](https://github.com/AppImage/AppImageKit/files/1528711/defective_appimage_for_testing.AppImage.zip)

**Comment by TheAssassin** [comment]
Well, the code used to be like tons of `void`s without any real error checks. Seems like the issue _is_ in appimaged, as it's not evaluating the return codes since most of that was changed to return actual values (`bool` or `int`).

**Comment by probonopd** [comment]
Again, appimaged should just tell libappimage "integrate this Appimage into the system" and not have anything to do with the implementation of the actual integration, which should entirely be handled by libappimage imho.

I am not saying that this is already the case, but that _should_ be how we do it.

appimaged, when done properly, would have almost no lines of code anymore. About the only thing it would be doing is watch directories with inotify and then call the appropriate libappimage functions.

**Comment by TheAssassin** [comment]
@probonopd what you say doesn't make any sense. Of course, it does only call the method to integrate AppImages...? But those functions have return values, and these return values should not be ignored, as they contain information whether the function succeeded or not.

I miss loads of basic error handling in this code base.

**Comment by probonopd** [comment]
What should appimaged do if libappimage returns an error on "integrate this Appimage into the system"? It should just proceed to the next AppImage, I guess.

**Comment by TheAssassin** [comment]
The issue here is that the value isn't evaluated properly, I'd say. appimaged is doing something wrong here, as libappimage never has ended up in a livelock before.

**Comment by probonopd** [comment]
Let's say it's a bug and someone needs to look into it :)

**Comment by TheAssassin** [comment]
That's what I implied 6 comments ago, yes...

**Comment by azubieta** [comment]
`appimaged` using `libappimage` v0.2 is now resilient to this issue and will not crash.
 Tested on Ubuntu 18.04. 

Reopen if the issue persists.
