### ISSUE TITLE
Build product ends up in src/

### ISSUE THREAD

**Issue by probonopd** [AppImage/appimaged#52]
Build product ends up in `src/` rather than the cwd. Something to do with CMake?

**Comment by TheAssassin** [comment]
That's not a bug. That's intentional. The files are in `src/`, and the build products are built there, too. As long as `make install` doesn't put them there, that's perfectly fine.

**Comment by TheAssassin** [comment]
CMake puts binaries next to the source files (or, rather, into the directory where the `CMakeLists.txt` is that declares them).

We can override the output path, and put them somewhere else, if you want to.

**Comment by probonopd** [comment]
Yes I'd prefer the build products to end up in (as the name implies) the build directory.

**Comment by TheAssassin** [comment]
> the build products

Well I'd only put the binaries in `bin/`, like many others configure their build scripts.

**Comment by probonopd** [comment]
That'd be fine too, but then I ask myself what is "build" for
