### ISSUE TITLE
Does not use desktop file symlinks correctly

### ISSUE THREAD

**Issue by probonopd** [AppImage/appimaged#54]
The the desktop file is a symlink, then it currently does not work. ([libappimage](https://github.com/AppImage/libappimage) should handle those implementation details, with no actual integration code to be left in `appimaged`.)

**Comment by probonopd** [comment]
https://github.com/AppImage/AppImageUpdate/blob/00053b7f8f8ff1e0693dff3015cb4ae5a42cfac8/resources/build-appimages.sh#L90 is why there is a symlink now, which is why AppImageUpdate no longer shows up in the menu.

It is a must that every AppImage core developer uses/tests with `appimaged` because I can get really angry if this gets broken.

**Comment by azubieta** [comment]
Fixed on `libappimage` v0.2. Reopen if the problem persists.
