### ISSUE TITLE
Appimages are not set executeable automatically

### ISSUE THREAD

**Issue by freddii** [AppImage/appimaged#57]
My AppImages are not set executeable automatically.

I am using Xubuntu 18.04 Bionic.
I installed the appimage of appimaged.

Everything else seams to work.

my terminal output:
_________________________

(appimaged:7559): GLib-CRITICAL **: 12:25:27.996: g_file_test: assertion 'filename != NULL' failed
Updating desktop...
gtk-update-icon-cache: The generated cache was invalid.
Warning: gtk-update-icon-cache retuned non-zero exit code:
kbuildsycoca5 running...
Finished updating desktop in 374 milliseconds.

**Comment by TheAssassin** [comment]
This is strange, as it's one of the core tasks of appimaged. @probonopd you merged a few changes to the integration code, can you please have a look?

**Comment by freddii** [comment]
i tested it in Xubuntu in virtualbox again.
Works there. 
Seams that its related to stuff i did on my system.
