### ISSUE TITLE
No x86_64 binary in Github releases.

### ISSUE THREAD

**Issue by luis-lavaire** [AppImage/appimaged#63]
There's no binary in the Github releases section for x86_64. Something may be broken on Travis, possibly; as there was one before.

**Comment by azubieta** [comment]
You can use the amd64 binaries, they are compatible.

**Comment by probonopd** [comment]
Triggered a new build, should be there again. Was seemingly an intermittent issue.

**Comment by luis-lavaire** [comment]
Thanks!
