### ISSUE TITLE
Appimage: g_file_test: assertion 'filename != NULL' failed

### ISSUE THREAD

**Issue by geext-dk** [AppImage/appimaged#64]
I've followed the install instructions in README.md and the appimage was installed without issues but it doesn't work. When I try to launch it from terminal, it outputs the following:
```
appimaged, continuous build (commit 369c33a), build 92 built on 2019-01-30 07:42:07 UTC
(appimaged:29979): GLib-CRITICAL **: 17:30:22.686: g_file_test: assertion 'filename != NULL' failed
Segmentation fault (core dumped)
```

OS: Fedora 29 (fully updated)

**Comment by geext-dk** [comment]
Nevermind. I've realised it's a duplicate of #58.

**Comment by TheAssassin** [comment]
The assertation is just a warning, I don't know exactly where it comes from. Must've been introduced in the last 6 months.

**Comment by probonopd** [comment]
Please try the solution given in https://github.com/AppImage/appimaged/issues /58#issuecomment-457636556 and please let us know whether it works for you.

If it does, we should consider to switch appimaged to libappimage 0.2 soon @TheAssassin @azubieta.
