### ISSUE TITLE
AppImage desktop integration files doesn't get removed

### ISSUE THREAD

**Issue by azubieta** [AppImage/appimaged#69]
the latest continious build from https://github.com/AppImage/appimaged/releases is not working for me.

$ ./appimaged-x86_64.AppImage -v
appimaged, continuous build (commit 86c09a7), build 96 built on 2019-02-26 16:37:28 UTC

I tryed it with:
https://github.com/X0rg/CPU-X/releases/download/v3.2.4/CPU-X_v3.2.4_x86_64.AppImage

if i put the appimage in ~/Applications it is adding the appimage correctly.
But if i remove the appimage, the starter does not get removed.

But the same process is working with appimaged from:
https://artifacts.assassinate-you.net/artifactory/appimaged/travis-87/appimaged-x86_64.AppImage
$ ./appimaged-x86_64.AppImage -n
appimaged, continuous build (commit c0332c8), build 87 built on 2019-01-22 06:58:18 UTC

_Originally posted by @freddii in https://github.com/AppImage/appimaged/issues/58#issuecomment-467682793_

**Comment by probonopd** [comment]
What has changed in between? Code in `libappimage` or also code in `appimaged`?

**Comment by azubieta** [comment]
Should be fixed at #70

**Comment by probonopd** [comment]
Thanks @azubieta. @fredfii can you confirm?

**Comment by azubieta** [comment]
This seems fixed, please reopen if the bug persist.
