### ISSUE TITLE
avidemux AppImage not detected, what am I missing?

### ISSUE THREAD

**Issue by priv** [AppImage/appimaged#75]
Hi All I'm new to appimaged.

I tried and KeepassXC and OpenShot application can be found on Ubuntu 18.10, but avidemux is not found.  So what should I do to allow it works correctly?

avidemux latest AppImage binary:
https://www.fosshub.com/Avidemux-old.html?dwl=avidemux_2.7.2.appImage

update:
I think the problem is that the desktop item created by appimaged is not complete(Type and Terminal are missing), why?

```
alvin@alvin-BM1AF:~/.local/share/applications$ cat appimagekit_8545d1ba158ad53de3d2decb0e4a2ecd-AVIDEMUX.desktop
[Desktop Entry]
Name=AVIDEMUX
Exec=/home/alvin/Applications/avidemux_2.7.2.appImage
Icon=appimagekit_8545d1ba158ad53de3d2decb0e4a2ecd_avidemux.png

TryExec=/home/alvin/Applications/avidemux_2.7.2.appImage
X-AppImage-Old-Icon=avidemux.png
X-AppImage-Identifier=8545d1ba158ad53de3d2decb0e4a2ecd
```

**Comment by probonopd** [comment]
Is Type present in the desktop file inside the AppImage? You can check with `--appimage-extract`.

**Comment by darealshinji** [comment]
`./avidemux_2.7.2.appImage --appimage-extract` just launches AviDemux and doesn extract anything.
Looking at the file header it seems to be made of the old AppImage format: `7F 45 4C 46 02 01 01 00 41 49 01 00 00 00 00 00`

**Comment by TheAssassin** [comment]
@darealshinji type 1 doesn't provide self-extraction, you need to use AppImageExtract, which can still be found on the release page on AppImageKit's GitHub page.

**Comment by probonopd** [comment]
Sorry, my bad. If it is a Type 1 AppImage then you can just loop-mount it.

**Comment by darealshinji** [comment]
Not a lot inside avidemux.desktop:
``` ini
[Desktop Entry]
Name=AVIDEMUX
Exec=avidemux3_portable
Icon=avidemux.png
```

**Comment by TheAssassin** [comment]
That file is clearly not conforming to the spec, as it's missing the `Type` key (here, it would be `Type=Application`). Maybe that's causing interoperability issues with your platform.

**Comment by priv** [comment]
Sorry I think there's nothing I could do so I'll close this one.

**Comment by probonopd** [comment]
> Sorry I think there's nothing I could do so I'll close this one.

Please ask the author of the AppImage to add the `Type=` key.
