### ISSUE TITLE
Cannot install appimaged

### ISSUE THREAD

**Issue by TriplexRoss** [AppImage/appimaged#90]
I'm developing a Linux distro called RonixOS which you can see my attempt at getting appimaged installed, currently fuse2 and fuse3 works under root but not my normal user on the dev environment. I read the documentation and it says the user needs to be in the fuse group but I am in the fuse group and I have the configuration to allow any user to use fuse in `/etc/fuse.conf`. I'm stuck any don't know anywhere else to ask for help except for here.
![Screenshot RonixOS](https://user-images.githubusercontent.com/19699320/58432387-fe1f6280-8066-11e9-9199-ef822407e546.png)

**Comment by probonopd** [comment]
> currently fuse2 and fuse3 works under root but not my normal user on the dev environment

Then that is what you need to fix in your operating system. We do now know how to do this in RonixOS.

**Comment by TriplexRoss** [comment]
RonixOS isn't really based on anything. The dev tools works like Arch Linux's but besides that, it's not like most distros.
