### ISSUE TITLE
Provide binaries for ARM 

### ISSUE THREAD

**Issue by jtc42** [AppImage/appimaged#96]
As in https://github.com/AppImage/AppImageKit/issues/111, it would be really useful to have ARM binary builds for use on things like the Raspberry Pi.

Given they're now available for AppImageKit, this would be particularly nice now.

**Comment by TheAssassin** [comment]
We're transitioning to AppImageLauncher, so we'll only add new architectures there then.

**Comment by jtc42** [comment]
Ah okay sorry! I thought the two were still completely separate. Thanks for letting me know!
