### ISSUE TITLE
$HOME/Applications not monitored

### ISSUE THREAD

**Issue by darealshinji** [AppImage/appimaged#97]
I move `Aegisub-8948-appimage-compat-7be4152-x86_64.AppImage` into "$HOME/Applications" and wait a bit, nothing happens.

`ls .local/share/applications/ | grep Aegisub` shows nothing.
I move it from "$HOME/Applications" into "$HOME/bin" and then it appears in the menu.

Output of `ls .local/share/applications/ | grep Aegisub`:
appimagekit_7ba51c53db07932fa06464b3bd7ea825-Aegisub.desktop

Seems like `$HOME/Applications` is not monitored, though the readme file says it should be.

**Comment by probonopd** [comment]
Strange. What happens when you move it back to `$HOME/Applications`?

**Comment by darealshinji** [comment]
I'm currently using https://github.com/TheAssassin/AppImageLauncher
