### ISSUE TITLE
can appimage be used to install appimaged to systemd 

### ISSUE THREAD

**Issue by sandys** [AppImage/appimaged#98]
hi guys,
just wanted to ask - can the appimage format be used to install appimaged to systemd ? I see there are multiple deb/rpm, etc format and im wondering why

**Comment by probonopd** [comment]
> can the appimage format be used to install appimaged to systemd

Yes it can.

> I see there are multiple deb/rpm, etc format and im wondering why

Unlike other applications that come in AppImages which do not need to be installed, `appimaged` is a system service that needs to be installed and registered with systemd. Hence it is not a typical use case for AppImage, and some users prefer traditional packages for system-level software.

**Comment by sandys** [comment]
Thanks for your reply.

There is a general perception that appimage cannot be used to install
system software (especially as a systemd service,etc).

Could you add support to install this through appimage itself ?

**Comment by probonopd** [comment]
AppImage is not intended for system software but for applications. For system software we generally recommend distribution packages.
